### ISSUE TITLE
Upload bug

### ISSUE THREAD

**Issue by crstn** [enviroCar/enviroCar-app#263]
I recorded a relatively long track yesterday and the recording worked fine. You can see the JSON export from the app here: https://gist.github.com/crstn/7923ceca845ee7bcc4c9

When I uploaded the track, only the very last small bit came through, though: https://envirocar.org/api/stable/tracks/561c62dae4b01fc4f7505492 

I tried to upload again, but then the app tells me that the track has already been uploaded (which is probably the correct behavior).

**Comment by dewall** [comment]
hi, 
could you pls provide some additional information about which version you are using and, in case you are using the most recent version from the github, an additional error report.

If you are using an older version of enviroCar (about 2-3 weeks old), we only can wait and see if the error recurs with a newer version, because I have rewritten the complete serialization and upload process of the app.

**Comment by crstn** [comment]
I was on the GSOC branch and just noticed that you're developing on the cleanup branch, so I installed that. I recorded a track and it doesn't show up under "My Tracks", so I can't test the upload.

**Comment by dewall** [comment]
the cleanup branch is currently a major reimplementation/restructuring of the app and this has not been extensively tested on various devices yet.

However, could you send us an error report for this issue?

**Comment by crstn** [comment]
Done. Which version of the app would you recommend to use at this point?

**Comment by dewall** [comment]
fixed ;)
