### ISSUE TITLE
App Always-On setting does not work anymore

### ISSUE THREAD

**Issue by dewall** [enviroCar/enviroCar-app#339]

**Comment by Hashik-Donthineni** [comment]
In my observation, it's still working when the app restarts that is,
- Change the setting 
- Restart the app
If you set the flag to true before restarting the app will prevent the screen from turning off and if you set it to false before restarting it'll not prevent the screen turn off which is expected functionality.

The problem comes when we change the setting and **didn't** restart the app the setting will not take effect.

**What I tried**: (In BaseMainActivityBottomBar.java class)
- We are launching another thread to set (or re-set) the flag from the onCreate method and then again calling the **checkKeepScreenOn()** in onPause, onResume I thought this is a synchronization problem, tried changing it to the main thread and the problem still persists.
