### ISSUE TITLE
Source of Regression coefficients values?

### ISSUE THREAD

**Issue by shumailxyz** [enviroCar/enviroCar-app#351]
Dear enviroCar Team

I was going through your code and trying to understand how fuel consumption is calculated for Diesel. I see that you use 3 regression coefficients in calculation of fuel consumption here: 
<br>
https://github.com/enviroCar/enviroCar-app/blob/master/org.envirocar.core/src/main/java/org/envirocar/core/trackprocessing/DieselConsumptionAlgorithm.java#L40

```
 private static final double CO_EFFICIENT_X1 = 0.23478;
 private static final double CO_EFFICIENT_X2 = 0.218911;
 private static final double CO_EFFICIENT_X3 = 0.18415;
```

Could you please share any details behind these values? How are these values calculated? Would be nice if you can share some thoughts or literature behind it. 

Thank you.

Regards,
Shumail

**Comment by dewall** [comment]
Dear Shumail,

this were the results from a test run trying to derive fuel consumption by using statistical methods. Unfortunately, in the evaluation phase of this regression function we observed that output of the output values were not in a reasonable marge of error. Therefore, we dismissed continuing this approach (long story). There is no thorough literature behind this. 

An alternative approach we are currently performing research on is the derivation of fuel consumption based on a more physical regression model. If you are also interested in this approach, then you can find the first test implementation in the develop branch here: 

https://github.com/enviroCar/enviroCar-app/blob/develop/org.envirocar.core/src/main/java/org/envirocar/core/trackprocessing/consumption/LoadBasedEnergyConsumptionAlgorithm.java

(of course we have a bunch of future improvements planned)

Best Regards,
Arne

**Comment by shumailxyz** [comment]
Dear Arne,

Thanks for the prompt reply.

I like the approach. Just thinking how realistic is the load based approach as it is very much dependent on vehicle specific parameters that could be hard to get in first place (height, width, mass, power use etc). From my understanding, it'd be possible to get these for the new connected vehicles but as a common approach is to just use OBD dongles, i doubt if the OBD dongles provide this information.

Do you think if this would be a problem?

Btw, not sure if it's interesting for you, but I was going through this paper yesterday that discusses the calculation of energy consumption for electric vehicles. Perhaps, could be of interest for you:
https://orbit.dtu.dk/en/publications/harnessing-big-data-for-estimating-the-energy-consumption-and-driving-range-of-electric-vehicles(b16f69e1-3b6d-4417-97b0-647384419b24).html

Thanks again for the reply.

Regards,
Shumail

**Comment by dewall** [comment]
Dear Shumail, 
you're welcome! 
Yeah, we know. The accuracy also depends on the difference in the altitude value and this value is not the most accurate parameter we get from the smartphones. However, we already have seen some promising results in estimating the actual fuel consumption even with this amount of approximation. This is just the first implementation that we could directly integrate. It is planned - as I mentioned before - to make some improvements in order to, for instance, include digital elevation models, street information, and at least some kind of categorization of cars when selecting a car. This would increase the accuracy. Ultimately, we would use the VIN (which is provided by the OBD protocol) to deduce the vehicle and its characteristics. But for this we would need a kind of service or database about the respective vehicles.

Btw.: Thanks for the paper! I'll take a look at this.

Best Regards,
Arne

**Comment by shumailxyz** [comment]
Dear Arne,

Thanks for sharing thoughts on that. I agree that it's complicated and good that you have plans for improvements.

Great project btw. Wish you guys all the best :) 

Regards,
Shumail
