### ISSUE TITLE
No option for password reset

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#396]
**Describe the bug**
No option to reset password  as it is present in web version.

**Comment by VibhorChinda** [comment]
@dewall sir  and @arvindnegi1 i would like to work on this issue if this is possible.

**Comment by arvindnegi1** [comment]
@dewall sir, is forget password implemented on backend ?

**Comment by dewall** [comment]
@VibhorChinda @arvindnegi1 it's a valid point that we are currently investigating on. However, the feature is currently for some reasons disabled. It will be reintegrated during the next weeks when we have some more time for this issue. But nevertheless, the feature hasn't been reintegrated on the app side so far.

**Comment by rahulshah456** [comment]
I would like to work on this issue if available

**Comment by asaikarthikeya** [comment]
I have placed all the requested features of sign in and sign up, that have to be implemented in the app-side and server-side under a single issue - #769. So that it will be easy of mentors to understand all the requested features by looking at one issue. Thanks for mentioning this feature @arvindnegi1 :)
