### ISSUE TITLE
Remove Unused Resources from the codebase

### ISSUE THREAD

**Issue by VibhorChinda** [enviroCar/enviroCar-app#404]
After running lint on the app module.
I found there are 231 resources which are unused that is they are increasing the size of the application and hindering application performance.

Solving it would basically help us to increase the efficiency of application.
i guess this should be treated asap.

@dewall sir waiting for your point of view on this.
if you allow i would like to work on it.

**Comment by VibhorChinda** [comment]
@dewall sir btw hope you don't mind me asking you that is it not necessary to get the issue being approved by you first then we provide a PR ?

Or like is it when we open an issue we can send the PR for it on the same time ?

**Comment by dewall** [comment]
hi @VibhorChinda,
I personally consider this issue to be important. It was already on my personal agenda. However, I would like this issue to be taken care of by myself, because I cannot estimate if something will be lost.

You can always issue pull requests which I will take care of. It then depends a little bit on the granularity of that pull request and the issue you targeted on how I will deal with the pull. Bigger issues need to be tested before merging and this is amostly very time consuming step. Also english/german translations is important. Otherwise, ones developments can lead to inconsistencies I would like to omit.

**Comment by VibhorChinda** [comment]
ok @dewall sir as you say so. Lets close this issue as you have this in mind already.

**Comment by VibhorChinda** [comment]
and @dewall sir i tried contacting you on the email address given but i got no response there. 
Seeing that you be very busy i thought i could ask for permission and guidance to start the challenge here.

Hope you won't mind this.

**Comment by dewall** [comment]
sorry, we had been on a retreat last week and therefore unavailable ;) see my personal mail

**Comment by asaikarthikeya** [comment]
@VibhorChinda As dewall sir has mentioned above, this issue will be handled by the code maintainers and owners of this project. Thank you for your suggestion.
