### ISSUE TITLE
Round off total distance to nearest integer in Dasboard fragment.

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#408]
**Describe the bug**
The total distance shown in dashboard fragment not round off to nearest integer.

**Screenshoot attached**
<img src="https://user-images.githubusercontent.com/33172321/74051200-8aa76080-49fd-11ea-9dbc-482d83dad982.png" height="500"></img>
- Considering image in current screenshoot the total distance traveled shown is <b>0 km</b>.
- Total distance covered is <b>0.8</b> its better to round off to nearest integer to show in dashboard fragment in this case <b>1 km</b> rather then <b>0 km </b>

**Comment by arvindnegi1** [comment]
@dewall  sir, is this valid point to work on? please put your point of view in this. :-)

**Comment by csk1827** [comment]
It is even more better if it is rounded off to one decimal place.

**Comment by arvindnegi1** [comment]
@csk1827 sir, thank you for your suggestion ;)

**Comment by dewall** [comment]
@arvindnegi1 it's a valid issue but rounding up to one decimal lead to more space required. Since this testview is autoscaling, one decimal would leads to significantly more space and this in turn leads to smaller textsizes on smaller devices. This, however, requires to make the autoscaling textviews to be syncronized. Finally, if you have 10k kilometers, the decimal number is actually unimportant.

**Comment by arvindnegi1** [comment]
Sir @dewall , can we round of this to nearest integer ? Like 9.3 km to 9 km in dashboard fragment and 9.8km to 10 km

**Comment by dewall** [comment]
thats okay I guess
