### ISSUE TITLE
GPS tracking details are not being updated in User statistics .

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#560]
###  **Description**

Currently when the user tracks his journey via GPS . The total tracks,distance,duration are not being updated .
This statistics are only updated for OBD Tracks.

###  **How I would like to fix**

1) Explicitly see GPS and OBD tracks.
Should I create new layout specifically for GPS such that when the User clicks on GPS TRACK the statistics are related to only GPS

2) Only one total tracks 
The total tracks referring to the sum of GPS+OBD.

**Comment by asaikarthikeya** [comment]
@arvindnegi1  Solving this issue, Which method would be a better choice (1 or 2)  to view the Total tracks?

**Comment by arvindnegi1** [comment]
@asaikarthikeya 
The GPS based recording is working fine but the issue here is with its not updating statistics. Its updating only when users logout and Login again.
And also on track recording finish based on GPS or OBD  TrackList not its updating only after user close app and re-open again.
Bothe the issue is because Fragment not refreshing.
duplicate issue #475 
Solved #499
