### ISSUE TITLE
Bug: LogBook Add Fueling

### ISSUE THREAD

**Issue by ritish099** [enviroCar/enviroCar-app#618]
As the Total price is automatically calculated on entering Mileage, Fueled Volume, Price Per Liter. Total Price editText should be disable for editing

<img src="https://user-images.githubusercontent.com/54978105/111508535-d33d5b80-8771-11eb-858b-12a6aa6b238d.jpg" width="333">

**Comment by ritish099** [comment]
I will be working on it

**Comment by Bhavya-22** [comment]
@ritish099 i would say that you should not remove it because it is vice versa case if you know litres and total price then you get price per litre or if you know litres and price per litre then you will get total price so its a good feature as most user remember the total amount not the price per litre so i suggest you should not remove the edit text field for total price.
Although choice is yours.

**Comment by ritish099** [comment]
@Bhavya-22 thanks for your thoughtful advice. but if you closely look at the Total price field. You will realize that you cannot enter more than 3 digits in Total Price field. but if you put Fulled volume to be 100 and price per litre to be 50 then u will get Total price to be 4 digit number(which is not possible by manually entering data). So either that is a bug or the makers did it intentionally to encourage people to get Total Price by entering the other two fields. 
Let any mentor see this issue.

**Comment by Bhavya-22** [comment]
@ritish099 ok I got your point. Thank you for considering my point

**Comment by asaikarthikeya** [comment]
I agree with @Bhavya-22 comment. User will remember the total price that he spent to fill fuel instead of the price per litre. And 
@ritish099, the app is mostly used in Germany were the fuel prices are in single digit Eg : € 1.39 per litre petrol. It makes sense that they have intentionally made the total price field to be just 3 digits. But in india the total fueling  cost can go upto 4 digits also as cost per litre petrol is more than 100 rupees. It is bit hard to maintain this as the cost of petrol per litre and total prices are quite different for different countries.

@SebaDro sir, Should i change the edit text length according to Indian fueling costs? This change might be helpful for indian contributors but this would be a potential downside for the users in germany. Please share you thoughts on this sir. Thank you ;)

**Comment by asaikarthikeya** [comment]
@ritish099 We had a internal discussion on this. We might implement #631, Sometime in the near feature. And regarding this issue, The total price should be changeable ( please refer my above comment). Feel free to ask if you have any further doubts regarding this. Thank you.
