### ISSUE TITLE
Availability of option for translating the text ( to maximize it's reach)

### ISSUE THREAD

**Issue by 07tAnYa** [enviroCar/enviroCar-app#999]
Description:
Now on the home page of enviro-car, there are some sections where German texts were there, which is fine but suppose someone who doesn't understand German will either go to an online translator or will leave that section. So to avoid this, we can add an option of Translate Text (a button) which will translate the text to English.

![Screenshot 2023-12-08 115614](https://github.com/enviroCar/enviroCar-app/assets/140234197/5272fe37-52da-4b6b-8737-62b7115e2adc)
How it might look after the modifications, I have reduced the size of the text by 10% over here:
![Screenshot 2023-12-08 120330](https://github.com/enviroCar/enviroCar-app/assets/140234197/ae3689a5-e3b6-4fdd-b2fd-1ea6ab9183a4)

**Comment by SebaDro** [comment]
Hi @07tAnYa . Thanks for your contribution and submitting this issue. However, I think the issue relates to the enviroCar Website, which has an own repository: https://github.com/enviroCar/enviroCar-landing-page.

I would be very happy, if you could move this issue to the landing page repo so that we can discuss it there. Please, also close the issue here, afterwards.
